kind: pipeline
name: default
type: docker

steps:
- name: release plugin
  image: plugins/docker
  settings:
    repo: plugins/drone-diagnostics
    dockerfile: docker/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true

trigger:
  event:
    - tag
    - refs/heads/master
