kind: pipeline
name: default
type: docker

steps:
- name: build plugin
  image: plugins/docker
  settings:
    repo: tphoney/drone-diagnostics
    dockerfile: docker/Dockerfile
    username: tphoney
    password:
      from_secret: docker_password
    # docker build -t tphoney/drone-diagnostics -f docker/Dockerfile .
- name: run tphoney/drone-diagnostics plugin
  image: tphoney/drone-diagnostics
  pull: if-not-exists
  commands:
    - env
    - ping www.github.com -w 5
    - traceroute -T -p 443 www.github.com
    - echo "end of test"