kind: pipeline
type: docker
name: default

- name: publish
  image: plugins/docker
  settings:
    repo: tphoney/drone-diagnostics
    auto_tag: true
    dockerfile: docker/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
